name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production  # Especifica o ambiente para usar os secrets

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script with secret
      run: |
        streamlit run chatbot_llm_openai.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
